name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Git commands
      run: |
        git config --global user.email "omprakashkartik82280@gmail.com"
        git config --global user.name "kom50"
        # git checkout -b om
        # git add .
        # git commit -m "Commit message"
        # git push origin om
    - name: Grant execute permissions to deploy.sh
      run: chmod +x deploy.sh
        ./deploy.sh
      env:
        github-token: ${{ secrets.GH_TOKEN }}
